### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by anjugopinath** [fredzzhang/upt#58]
Hi,

I am getting an error on executing inference.py -> the command given on the github site.

<img width="937" alt="image" src="https://user-images.githubusercontent.com/4654298/193421143-cecdb6f6-379c-4b3b-a171-dbf02705cc8e.png">

**Comment by fredzzhang** [comment]
Hi @anjugopinath,

As suggested by the print message, you are using a randomly initialised model. To load the provided model, you need to download the UPT checkpoints and place them under the directory `checkpoints`.

If the checkpoints are placed under the correct path, you should see `Continue from saved checkpoint ./checkpoints/upt-r50-hicodet.pt` printed instead of `Start from a randomly initialised model`.

Fred.

**Comment by anjugopinath** [comment]
That worked. Thank You.
