### ISSUE TITLE
train

### ISSUE THREAD

**Issue by wangjunbianqiang** [fredzzhang/upt#71]
python main.py --world-size 1 --pretrained checkpoints/detr-r50-hicodet.pth --output-dir checkpoints/upt-r50-hicodet

raise ValueError(f"The HOI loss is NaN for rank {self._rank}")
ValueError: The HOI loss is NaN for rank 0

**Comment by fredzzhang** [comment]
Hi @wangjunbianqiang,

The spatial head in the model tends to have unstable statistics, which will cause numeric overflow in certain layers, ultimately resulting in the loss being `nan`.

This can be easily solved by increasing the batch size, which will help stabilise the statistics. Since you are only using 1 GPU, you need to increase the batch size by 8 times with the flag `--batch-size 16`.

Fred.

**Comment by wangjunbianqiang** [comment]
Oh，thanks!
